import createNextIntlPlugin from 'next-intl/plugin';
const withNextIntl = createNextIntlPlugin();
/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "http",
        hostname: "admin.rollmatic.com",
        pathname: "/wp-content/uploads/**", // This is for WP
      },
      {
        protocol: "https",
        hostname: "rollmatic.375.studio",
        pathname: "/wp-content/uploads/**", // This is for WP
      },
    ],
    
  },
  async redirects() {
    return [
      // ===== ITALIANO (locale di default, senza prefisso) (93) =====
      {
        source: "/cookie-policy",
        destination: "/",
        permanent: false,
        locale: false,
      },
      {
        source: "/mappa-del-sito",
        destination: "/",
        permanent: true,
        locale: false,
      },
      {
        source: "/in-pronta-consegna",
        destination: "/pronta-consegna",
        permanent: true,
        locale: false,
      },
      {
        source: "/condizioni-di-vendita",
        destination: "/",
        permanent: true,
        locale: false,
      },
      {
        source: "/profilo-aziendale",
        destination: "/azienda",
        permanent: true,
        locale: false,
      },
      {
        source: "/note-legali",
        destination: "/",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/disclaimer",
        destination: "/",
        permanent: true,
        locale: false,
      },
      {
        source: "/privacy",
        destination: "/",
        permanent: true,
        locale: false,
      },
      {
        source: "/spezzatrice-arrotondatrice",
        destination: "/spezza-arrotondatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierina-per-pane",
        destination: "/taglierine",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrice/macchine-pasta-sfoglia",
        destination: "/sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetaria/mixer-planetario",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali",
        destination: "/sfogliatrici-manuali-professionali",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-automatiche",
        destination: "/sfogliatrici-automatiche-professionali",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/mescolatori-planetari",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrice/laminatoio-pasta",
        destination: "/sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/spezza-arrotondatrici/spezza-arrotondatrici-automatiche",
        destination: "/spezza-arrotondatrici-automatiche",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrice",
        destination: "/sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/spezza-arrotondatrici/spezza-arrotondatrici-semi-automatiche",
        destination: "/spezza-arrotondatrici-semi-automatiche",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-industriali",
        destination: "/taglierine-industriali-per-pane",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/sigep-ab-tech-expo-2020",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-da-banco",
        destination: "/taglierine",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetaria/sbattitore-planetario",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrice/macchina-croissant",
        destination: "/sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/video-abtech-sigep-2013",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/sollevatori-vasca",
        destination: "/sollevatori-vasca-per-impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/tavoli-da-lavoro",
        destination: "/tavoli-da-lavoro-per-sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/bakery-china-expo-2019",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetaria/mescolatrice-pasta",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrice/sfogliatrice-pasta-sfoglia",
        destination: "/sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-a-passo-variabile",
        destination: "/taglierine-automatiche-spessore-variabile",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/video-sigep-ab-tech-expo-2017",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/macina-pane",
        destination: "/macina-pane-professionale",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetaria/impastatrice",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-automatiche/r65axp-r65axp-t",
        destination: "/sfogliatrici/r65axp-r65axp-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali-compatte",
        destination: "/sfogliatrici-manuali-compatte",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetaria/miscelatore-pasta",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierina-per-pane/affettatrice-pane",
        destination: "/taglierine",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-con-base",
        destination: "/taglierine-semiautomatiche-passo-fisso",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/host-2019",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-semi-automatiche",
        destination: "/sfogliatrici-semi-automatiche",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrice/laminazione-pasta",
        destination: "/sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/video-abtech-sigep-2015",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/intersicop-2019",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/melbourne-1-premio-innovazione",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrice/macchina-pasta-frolla",
        destination: "/sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetaria",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrice/laminatrice-pasta-sfoglia",
        destination: "/sfogliatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/video-spezza-arrotondatrici-diro",
        destination: "/spezza-arrotondatrici",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/soffiatore-per-insacchettamento",
        destination: "/soffiatore-per-insacchettamento-pane",
        permanent: true,
        locale: false,
      },
      {
        source: "/spezza-arrotondatrici/spezza-arrotondatrici-manuali",
        destination: "/spezza-arrotondatrici-manuali",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/mescolatori-planetari/b60-b60p",
        destination: "/impastatrici-planetarie/b60-b60p",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-a-passo-variabile/s40s-s50s",
        destination: "/taglierine/s40-s-s50-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/macina-pane/bm11",
        destination: "/taglierine/bm11",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-da-banco/c42-c52",
        destination: "/taglierine/c42-c52",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-da-banco/cp42-pl",
        destination: "/taglierine/cp42-pl",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali-compatte/r50",
        destination: "/sfogliatrici/r50",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/mescolatori-planetari/b80l",
        destination: "/impastatrici-planetarie/b80l",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-semi-automatiche/r65s-r65s-t",
        destination: "/sfogliatrici/r65s-r65s-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali/r60-r60-t",
        destination: "/sfogliatrici/r60-r60-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/tavoli-da-lavoro/tb30-35",
        destination: "/sfogliatrici/tb30-tb35",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali-compatte/r50b",
        destination: "/sfogliatrici/r50b",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/mescolatori-planetari/b10",
        destination: "/impastatrici-planetarie",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-con-base/cp42s-cp52s",
        destination: "/taglierine/cp42-s-cp52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-industriali/mi52",
        destination: "/taglierine/mi52",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali-compatte/s5bm",
        destination: "/sfogliatrici/s5bm",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-da-banco/g42",
        destination: "/taglierine/g42",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-automatiche/r65a-r65a-t",
        destination: "/sfogliatrici/r65a-r65a-t-6",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/mescolatori-planetari/b40l-b40p",
        destination: "/impastatrici-planetarie/b40p",
        permanent: true,
        locale: false,
      },
      {
        source: "/spezza-arrotondatrici/spezza-arrotondatrici-automatiche/dr-a",
        destination: "/spezza-arrotondatrici/dr-a",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/mescolatori-planetari/b60l",
        destination: "/impastatrici-planetarie/b60l",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali/r65-r65-t",
        destination: "/sfogliatrici/r65-r65-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-automatiche/r65ax-r65ax-t",
        destination: "/sfogliatrici/r65ax-r65ax-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/sollevatori-vasca/soll-100-160",
        destination: "/impastatrici-planetarie/soll100-soll160",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-industriali/mr52",
        destination: "/taglierine/mr52",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-a-passo-variabile/s40-s50",
        destination: "/taglierine/s40-s50",
        permanent: true,
        locale: false,
      },
      {
        source: "/planetarie/mescolatori-planetari/b100-b160",
        destination: "/impastatrici-planetarie/b100-b160",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali-compatte/r55",
        destination: "/sfogliatrici/r55",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali/r62-r62-t",
        destination: "/sfogliatrici/r62-r62-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/sfogliatrici/sfogliatrici-manuali-compatte/r55b",
        destination: "/sfogliatrici/r55b",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-con-base/c42s-c52s",
        destination: "/taglierine/c42-s-c52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/spezza-arrotondatrici/spezza-arrotondatrici-manuali/dr-m",
        destination: "/spezza-arrotondatrici/dr-m",
        permanent: true,
        locale: false,
      },
      {
        source: "/spezza-arrotondatrici/spezza-arrotondatrici-semi-automatiche/dr-s",
        destination: "/spezza-arrotondatrici/dr-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/macina-pane/mac100",
        destination: "/taglierine/mac100",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/soffiatore-per-insacchettamento/aps-fs",
        destination: "/taglierine/aps-fs",
        permanent: true,
        locale: false,
      },
      {
        source: "/taglierine/taglierine-da-banco/cp42-cp52",
        destination: "/taglierine/cp42-cp52",
        permanent: true,
        locale: false,
      },
      {
        source: "/viewerjs",
        destination: "/",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/nuova-generazione-di-taglierine-a-passo-variabile",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/news/r65axp-4-0",
        destination: "/news",
        permanent: true,
        locale: false,
      },
      // ===== ENGLISH (80) =====
      {
        source: "/en/sitemap",
        destination: "/en",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/available-in-stock",
        destination: "/en/ready-for-delivery",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers",
        destination: "/en/bread-slicers",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sales-terms-and-conditions",
        destination: "/en",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/divider-rounders",
        destination: "/en/dough-divider-rounders",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/legal-notes",
        destination: "/en",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/disclaimer",
        destination: "/en",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers",
        destination: "/en/planetary-mixers",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/company-profile",
        destination: "/en/company",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/privacy",
        destination: "/en",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters",
        destination: "/en/dough-sheeters",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/divider-rounder",
        destination: "/en/dough-divider-rounders",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/sigep-abtech-2023",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/iba-2025",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-dough-sheeters",
        destination: "/en/professional-manual-dough-sheeters",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/automatic-dough-sheeters",
        destination: "/en/professional-automatic-dough-sheeters",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/planetary-mixers",
        destination: "/en/planetary-mixers",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/divider-rounders/automatic-divider-rounder",
        destination: "/en/automatic-dough-divider-rounders",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/dough-sheeter",
        destination: "/en/dough-sheeters",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/divider-rounders/semi-automatic-divider-rounder",
        destination: "/en/semi-automatic-dough-divider-rounders",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/industrial-bread-slicers",
        destination: "/en/industrial-bread-slicers",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/sigep-ab-tech-expo-2020",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bench-type-bread-slicers",
        destination: "/en/semi-automatic-bread-slicers-fixed-thickness",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/video-abtech-sigep-2013",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/bowl-lifter-planetary-mixers",
        destination: "/en/bowl-lifters-for-planetary-mixers",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/bakery-china-expo-2019",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/tables",
        destination: "/en/dough-sheeter-work-tables",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/video-sigep-ab-tech-expo-2017",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bread-slicers-variable-pitch",
        destination: "/en/automatic-bread-slicers-variable-thickness",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bread-mill",
        destination: "/en/professional-bread-mills",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/automatic-dough-sheeters/r65axp-r65axp-t",
        destination: "/en/dough-sheeters/r65axp-r65axp-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-compact-dough-sheeters",
        destination: "/en/professional-manual-dough-sheeters",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/host-2019",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/free-standing-bread-slicers",
        destination: "/en/semi-automatic-bread-slicers-fixed-thickness",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/video-abtech-sigep-2015",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/intersicop-2019",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/melbourne-1st-prize-for-the-innovation",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/semi-automatic-dough-sheeters",
        destination: "/en/semi-automatic-dough-sheeters",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/video-diro-divider-rounders",
        destination: "/en/dough-divider-rounders",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/planetary-mixer",
        destination: "/en/planetary-mixers",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/divider-rounders/manual-divider-rounder",
        destination: "/en/manual-dough-divider-rounders",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bag-blower-for-packaging",
        destination: "/en/bread-bagging-blower",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/planetary-mixers/b60-b60p",
        destination: "/en/planetary-mixers/b60-b60p",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bread-slicers-variable-pitch/s40s-s50s",
        destination: "/en/bread-slicers/s40-s-s50-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bread-mill/bm11",
        destination: "/en/bread-slicers/bm11",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bench-type-bread-slicers/c42-c52",
        destination: "/en/bread-slicers/c42-c52",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/r65axp-4-0",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/news/new-generation-of-bread-slicers-with-variable-pitch",
        destination: "/en/news",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/divider-rounders/manual-divider-rounder/dr-m",
        destination: "/en/dough-divider-rounders/dr-m",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bag-blower-for-packaging/aps-fs",
        destination: "/en/bread-slicers/aps-fs",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-dough-sheeters/r62-r62-t",
        destination: "/en/dough-sheeters/r62-r62-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/free-standing-bread-slicers/c42s-c52s",
        destination: "/en/bread-slicers/c42-s-c52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-compact-dough-sheeters/r55b",
        destination: "/en/dough-sheeters/r55b",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/divider-rounders/semi-automatic-divider-rounder/dr-s",
        destination: "/en/dough-divider-rounders/dr-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bread-mill/mac100",
        destination: "/en/bread-slicers/mac100",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-compact-dough-sheeters/r55",
        destination: "/en/dough-sheeters/r55",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bench-type-bread-slicers/cp42-cp52",
        destination: "/en/bread-slicers/cp42-cp52",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/planetary-mixers/b100-b160",
        destination: "/en/planetary-mixers/b100-b160",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bread-slicers-variable-pitch/s40-s50",
        destination: "/en/bread-slicers/s40-s50",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/bowl-lifter-planetary-mixers/soll-100-160",
        destination: "/en/planetary-mixers/soll100-soll160",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/industrial-bread-slicers/mr52",
        destination: "/en/bread-slicers/mr52",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/automatic-dough-sheeters/r65ax-r65ax-t",
        destination: "/en/dough-sheeters/r65ax-r65ax-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-dough-sheeters/r65-r65-t",
        destination: "/en/dough-sheeters/r65-r65-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/planetary-mixers/b60l",
        destination: "/en/planetary-mixers/b60l",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/divider-rounders/automatic-divider-rounder/dr-a",
        destination: "/en/dough-divider-rounders/dr-a",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/planetary-mixers/b40l-b40p",
        destination: "/en/planetary-mixers/b40p",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/automatic-dough-sheeters/r65a-r65a-t",
        destination: "/en/dough-sheeters/r65a-r65a-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bench-type-bread-slicers/g42",
        destination: "/en/bread-slicers/g42",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-compact-dough-sheeters/s5bm",
        destination: "/en/dough-sheeters/s5bm",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/industrial-bread-slicers/mi52",
        destination: "/en/bread-slicers/mi52",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/planetary-mixers/b10",
        destination: "/en/planetary-mixers",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/free-standing-bread-slicers/cp42s-cp52s",
        destination: "/en/bread-slicers/cp42-s-cp52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-compact-dough-sheeters/r50b",
        destination: "/en/dough-sheeters/r50b",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/tables/tb30-35",
        destination: "/en/dough-sheeters/tb30-tb35",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-dough-sheeters/r60-r60-t",
        destination: "/en/dough-sheeters/r60-r60-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/semi-automatic-dough-sheeters/r65s-r65s-t",
        destination: "/en/dough-sheeters/r65s-r65s-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/mixers/planetary-mixers/b80l",
        destination: "/en/planetary-mixers/b80l",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/sheeters/manual-compact-dough-sheeters/r50",
        destination: "/en/dough-sheeters/r50",
        permanent: true,
        locale: false,
      },
      {
        source: "/en/slicers/bench-type-bread-slicers/cp42-pl",
        destination: "/en/bread-slicers/cp42-pl",
        permanent: true,
        locale: false,
      },
      // ===== FRANÇAIS (83) =====
      {
        source: "/fr/conditions-generales-de-vente",
        destination: "/fr",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/profil",
        destination: "/fr/agence",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/contactez-nous",
        destination: "/fr/contacts",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/avertissement",
        destination: "/fr",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur",
        destination: "/fr/melangeurs-planetaires",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/diviseuse-bouleuse",
        destination: "/fr/diviseuses-bouleuses",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/legal-notes",
        destination: "/fr",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/blog-news",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/privacy",
        destination: "/fr",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain",
        destination: "/fr/trancheuses-a-pain",
        permanent: true,
        locale: false,
      },
      // -> /fr/prêt-à-être-livré
      {
        source: "/fr/available-in-stock",
        destination: "/fr/pr%C3%AAt-%C3%A0-%C3%AAtre-livr%C3%A9",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs",
        destination: "/fr/laminoirs-a-pate",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/sitemap",
        destination: "/fr",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/intersicop-2019",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/sigep-ab-tech-expo-2020",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/bakery-china-expo-2019",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/melbourne-1st-prize-for-the-innovation",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/iba-2025",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/host-2019",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/video-sigep-ab-tech-expo-2017",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/video-abtech-sigep-2015",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/r65axp-4-0",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/nouvelle-generation-de-trancheuses-a-pain-a-pas-variable",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/video-abtech-sigep-2013",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/news/sigep-abtech-2023",
        destination: "/fr/nouvelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels-compacts/r55",
        destination: "/fr/laminoirs-a-pate/r55",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels-compacts/r50b",
        destination: "/fr/laminoirs-a-pate/r50b",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-automatiques/r65ax-r65ax-t",
        destination: "/fr/laminoirs-a-pate/r65ax-r65ax-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-industrielles/mi52",
        destination: "/fr/trancheuses-a-pain/mi52",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-automatiques/r65axp-r65axp-t",
        destination: "/fr/laminoirs-a-pate/r65axp-r65axp-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/diviseuse-bouleuse/diviseuse-bouleuse-automatique",
        destination: "/fr/diviseuses-bouleuses-automatiques",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-industrielles",
        destination: "/fr/trancheuses-a-pain-industrielles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/melangeurs-planetaires/b60l",
        destination: "/fr/melangeurs-planetaires/b60l",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/melangeurs-planetaires/b10",
        destination: "/fr/melangeurs-planetaires",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-avec-base",
        destination: "/fr/trancheuses-a-pain-semi-automatiques-epaisseur-fixe",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels-compacts/s5bm",
        destination: "/fr/laminoirs-a-pate/s5bm",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-avec-base/c42s-c52s",
        destination: "/fr/trancheuses-a-pain/c42-s-c52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels",
        destination: "/fr/laminoirs-manuels-professionnels",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/moulin-pour-pain",
        destination: "/fr/moulins-a-pain-professionnels",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/souffleuse-pour-ensachage/aps-fs",
        destination: "/fr/trancheuses-a-pain/aps-fs",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-a-pain-a-pas-variable",
        destination: "/fr/trancheuses-a-pain-automatiques-epaisseur-variable",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels/r62-r62-t",
        destination: "/fr/laminoirs-a-pate/r62-r62-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/melangeurs-planetaires",
        destination: "/fr/melangeurs-planetaires",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/moulin-pour-pain/mac100",
        destination: "/fr/trancheuses-a-pain/mac100",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/moulin-pour-pain/bm11",
        destination: "/fr/trancheuses-a-pain/bm11",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/dispositif-de-soulevement-cuves",
        destination: "/fr/dispositif-de-soulevement-cuves-pour-melangeurs-planetaires",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-avec-base/cp42s-cp52s",
        destination: "/fr/trancheuses-a-pain/cp42-s-cp52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/diviseuse-bouleuse/diviseuse-bouleuse-automatique/dr-a",
        destination: "/fr/diviseuses-bouleuses/dr-a",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/tables/tb30-35",
        destination: "/fr/laminoirs-a-pate/tb30-tb35",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/melangeurs-planetaires/b100-b160",
        destination: "/fr/melangeurs-planetaires/b100-b160",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels-compacts/r55b",
        destination: "/fr/laminoirs-a-pate/r55b",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/diviseuse-bouleuse/diviseuse-bouleuse-semi-automatique",
        destination: "/fr/diviseuses-bouleuses-semi-automatiques",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels-compacts",
        destination: "/fr/laminoirs-manuels-professionnels",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/melangeurs-planetaires/b80l",
        destination: "/fr/melangeurs-planetaires/b80l",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-automatiques/r65a-r65a-t",
        destination: "/fr/laminoirs-a-pate/r65a-r65a-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-a-pain-a-pas-variable/s40-s50",
        destination: "/fr/trancheuses-a-pain/s40-s50",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-a-pain-a-pas-variable/s40s-s50s",
        destination: "/fr/trancheuses-a-pain/s40-s-s50-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/diviseuse-bouleuse/diviseuse-bouleuse-manuelle/dr-m",
        destination: "/fr/diviseuses-bouleuses/dr-m",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/dispositif-de-soulevement-cuves/soll-100-160",
        destination: "/fr/melangeurs-planetaires/soll100-soll160",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels/r60-r60-t",
        destination: "/fr/laminoirs-a-pate/r60-r60-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels-compacts/r50",
        destination: "/fr/laminoirs-a-pate/r50",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-semi-automatiques/r65s-r65s-t",
        destination: "/fr/laminoirs-a-pate/r65s-r65s-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-pour-comptoir/cp42-cp52",
        destination: "/fr/trancheuses-a-pain/cp42-cp52",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-pour-comptoir/c42-c52",
        destination: "/fr/trancheuses-a-pain/c42-c52",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-industrielles/mr52",
        destination: "/fr/trancheuses-a-pain/mr52",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/tables",
        destination: "/fr/tables-de-travail-pour-laminoirs",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/melangeurs-planetaires/b40l-b40p",
        destination: "/fr/melangeurs-planetaires/b40p",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-manuels/r65-r65-t",
        destination: "/fr/laminoirs-a-pate/r65-r65-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/souffleuse-pour-ensachage",
        destination: "/fr/souffleuse-pour-ensachage-pain",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/diviseuse-bouleuse/diviseuse-bouleuse-semi-automatique/dr-s",
        destination: "/fr/diviseuses-bouleuses/dr-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-pour-comptoir/g42",
        destination: "/fr/trancheuses-a-pain/g42",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-pour-comptoir",
        destination: "/fr/trancheuses-a-pain-semi-automatiques-epaisseur-fixe",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/batteur-melangeur/melangeurs-planetaires/b60-b60p",
        destination: "/fr/melangeurs-planetaires/b60-b60p",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/diviseuse-bouleuse/diviseuse-bouleuse-manuelle",
        destination: "/fr/diviseuses-bouleuses-manuelles",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-automatiques",
        destination: "/fr/laminoirs-automatiques-professionnels",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoirs/laminoirs-semi-automatiques",
        destination: "/fr/laminoirs-semi-automatiques",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuses-a-pain/coupeuses-pour-comptoir/cp42-pl",
        destination: "/fr/trancheuses-a-pain/cp42-pl",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/coupeuse-a-pain",
        destination: "/fr/trancheuses-a-pain",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/video-diro-diviseuses-bouleuses",
        destination: "/fr/diviseuses-bouleuses",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/melangeur-planetaire",
        destination: "/fr/melangeurs-planetaires",
        permanent: true,
        locale: false,
      },
      {
        source: "/fr/laminoir-a-pate",
        destination: "/fr/laminoirs-a-pate",
        permanent: true,
        locale: false,
      },
      // ===== DEUTSCH (86) =====
      {
        source: "/de/sitemap",
        destination: "/de",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/available-in-stock",
        destination: "/de/lieferbereit",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/unternehmensprofil",
        destination: "/de/agentur",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/sales-terms-and-conditions",
        destination: "/de",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/disclaimer",
        destination: "/de",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/privacy",
        destination: "/de",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke",
        destination: "/de/planetenmischer",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/blog-news",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/legal-notes",
        destination: "/de",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/teilteig-und-wirkmaschine",
        destination: "/de/teigteiler-und-wirker",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/host-2025",
        destination: "/de/nachricht/host-2025",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/teigteiler-und-rundwirker",
        destination: "/de/teigteiler-und-wirker",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/sigep-abtech-2023",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschine",
        destination: "/de/brotschneidemaschinen",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschine/pizza-ausrollmaschine",
        destination: "/de/pizza",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/iba-2025",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-ausrollmaschinen",
        destination: "/de/professionelle-handbucher",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/automatische-ausrollmaschinen",
        destination: "/de/professionelle-automatische-teig-blattblieder",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/planetenruhrwerke",
        destination: "/de/planetenmischer",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschine",
        destination: "/de/ausrollmaschinen",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/teilteig-und-wirkmaschine/vollautomatische-teilteig-und-wirkmaschine",
        destination: "/de/automatische-teigteiler-und-wirker",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/teilteig-und-wirkmaschine/halbautomatische-teilteig-und-wirkmaschine",
        destination: "/de/halbautomatische-teigteiler-und-wirker",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/sigep-ab-tech-expo-2020",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-industriemodelle",
        destination: "/de/industrielle-brotfraser",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschine/konditorei-ausrollmaschinen",
        destination: "/de/konditorei",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-tischmodelle",
        destination: "/de/halbautomatische-fix-pitch-brotschneidemaschinen",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/video-abtech-sigep-2013",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/kesselhohensystem",
        destination: "/de/schalenheber-fur-planetenmischer",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/arbeitstische",
        destination: "/de/arbeitstische-fur-teigblattblieder",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/video-diro-teigteiler-und-rundwirker",
        destination: "/de/teigteiler-und-wirker",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/bakery-china-expo-2019",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerk/planetenruhrmaschine",
        destination: "/de/planetenmischer",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/video-abtech-sigep-2015",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/veranderbare-schnittstarke-brotschneidemaschinen",
        destination: "/de/automatische-fraser-mit-variabler-dicke",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/intersicop-2019",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerk",
        destination: "/de/planetenmischer",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/semmelbroselmaschinen",
        destination: "/de/professioneller-brotwolf",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-sockelmodelle",
        destination: "/de/halbautomatische-fix-pitch-brotschneidemaschinen",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/video-sigep-ab-tech-expo-2017",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/teilteig-und-wirkmaschine/manuelle-teilteig-und-wirkmaschine",
        destination: "/de/manuelle-teigteiler-und-wirker",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/halbautomatische-ausrollmaschinen",
        destination: "/de/halbautomatische-teiggerate",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschine/backerei-ausrollmaschinen",
        destination: "/de/baeckerei",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/bag-blower-for-packaging",
        destination: "/de/brotbeutel-geblase",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschine/brot-aufschnittmaschine",
        destination: "/de/brotschneidemaschinen",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/automatische-ausrollmaschinen/r65axp-r65axp-t",
        destination: "/de/ausrollmaschinen/r65axp-r65axp-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/host-2019",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/melbourne-1st-prize-for-the-innovation",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-kompakte-ausrollmaschinen",
        destination: "/de/professionelle-handbucher",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/bag-blower-for-packaging/aps-fs",
        destination: "/de/brotschneidemaschinen/aps-fs",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-kompakte-ausrollmaschinen/r50",
        destination: "/de/ausrollmaschinen/r50",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/veranderbare-schnittstarke-brotschneidemaschinen/s40-s50",
        destination: "/de/brotschneidemaschinen/s40-s50",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/planetenruhrwerke/b60-b60p",
        destination: "/de/planetenmischer/b60-b60p",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/planetenruhrwerke/b60l",
        destination: "/de/planetenmischer/b60l",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/teilteig-und-wirkmaschine/vollautomatische-teilteig-und-wirkmaschine/dr-a",
        destination: "/de/teigteiler-und-wirker/dr-a",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-industriemodelle/mi52",
        destination: "/de/brotschneidemaschinen/mi52",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-sockelmodelle/c42s-c52s",
        destination: "/de/brotschneidemaschinen/c42-s-c52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/planetenruhrwerke/b80l",
        destination: "/de/planetenmischer/b80l",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/semmelbroselmaschinen/bm11",
        destination: "/de/brotschneidemaschinen/bm11",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-tischmodelle/g42",
        destination: "/de/brotschneidemaschinen/g42",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/planetenruhrwerke/b40l-b40p",
        destination: "/de/planetenmischer/b40p",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/teilteig-und-wirkmaschine/halbautomatische-teilteig-und-wirkmaschine/dr-s",
        destination: "/de/teigteiler-und-wirker/dr-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/kesselhohensystem/soll-100-160",
        destination: "/de/planetenmischer/soll100-soll160",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-kompakte-ausrollmaschinen/s5bm",
        destination: "/de/ausrollmaschinen/s5bm",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/planetenruhrwerke/b10",
        destination: "/de/planetenmischer",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-sockelmodelle/cp42s-cp52s",
        destination: "/de/brotschneidemaschinen/cp42-s-cp52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-tischmodelle/c42-c52",
        destination: "/de/brotschneidemaschinen/c42-c52",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/veranderbare-schnittstarke-brotschneidemaschinen/s40s-s50s",
        destination: "/de/brotschneidemaschinen/s40-s-s50-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-ausrollmaschinen/r65-r65-t",
        destination: "/de/ausrollmaschinen/r65-r65-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-ausrollmaschinen/r62-r62-t",
        destination: "/de/ausrollmaschinen/r62-r62-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/automatische-ausrollmaschinen/r65a-r65a-t",
        destination: "/de/ausrollmaschinen/r65a-r65a-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/automatische-ausrollmaschinen/r65ax-r65ax-t",
        destination: "/de/ausrollmaschinen/r65ax-r65ax-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-industriemodelle/mr52",
        destination: "/de/brotschneidemaschinen/mr52",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-ausrollmaschinen/r60-r60-t",
        destination: "/de/ausrollmaschinen/r60-r60-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/halbautomatische-ausrollmaschinen/r65s-r65s-t",
        destination: "/de/ausrollmaschinen/r65s-r65s-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/teilteig-und-wirkmaschine/manuelle-teilteig-und-wirkmaschine/dr-m",
        destination: "/de/teigteiler-und-wirker/dr-m",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-kompakte-ausrollmaschinen/r55b",
        destination: "/de/ausrollmaschinen/r55b",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/planetenruhrwerke/planetenruhrwerke/b100-b160",
        destination: "/de/planetenmischer/b100-b160",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-kompakte-ausrollmaschinen/r50b",
        destination: "/de/ausrollmaschinen/r50b",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/manuelle-kompakte-ausrollmaschinen/r55",
        destination: "/de/ausrollmaschinen/r55",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-tischmodelle/cp42-pl",
        destination: "/de/brotschneidemaschinen/cp42-pl",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/ausrollmaschinen/arbeitstische/tb30-35",
        destination: "/de/ausrollmaschinen/tb30-tb35",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/brotschneidemaschinen-tischmodelle/cp42-cp52",
        destination: "/de/brotschneidemaschinen/cp42-cp52",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/r65axp-4-0",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/brotschneidemaschinen/semmelbroselmaschinen/mac100",
        destination: "/de/brotschneidemaschinen/mac100",
        permanent: true,
        locale: false,
      },
      {
        source: "/de/news/neue-generation-brotschneidemaschinen-mit-variabler-teilung",
        destination: "/de/nachricht",
        permanent: true,
        locale: false,
      },
      // ===== ESPAÑOL (86) =====
      {
        source: "/es/blog-news",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/aviso-legal",
        destination: "/es",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/privacy",
        destination: "/es",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/sitemap",
        destination: "/es",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/available-in-stock",
        destination: "/es/listo-para-entrega",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras",
        destination: "/es/cortadoras-de-pan",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/sales-terms-and-conditions",
        destination: "/es",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/profilo",
        destination: "/es/agencia",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/contacto",
        destination: "/es/contactos",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/host-2025",
        destination: "/es/host-2025",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/legal-notes",
        destination: "/es",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras",
        destination: "/es/batidoras-planetarias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras-boleadoras",
        destination: "/es/divisora-boleadora",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/sigep-abtech-2023",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadora-de-pan",
        destination: "/es/cortadoras-de-pan",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidora-planetaria/mezclador-planetario",
        destination: "/es/batidoras-planetarias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadora-de-masa/laminadora-pasteleria",
        destination: "/es/sectores/pasteleria",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales",
        destination: "/es/laminadoras-manuales",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/iba-2025",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-automaticas",
        destination: "/es/laminadoras-automaticas",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/mezcladores-planetarios",
        destination: "/es/batidoras-planetarias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/divisora-boleadora/divisora-boleadora-automatica",
        destination: "/es/divisora-boleadora-automatica",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadora-de-masa",
        destination: "/es/laminadoras",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/divisora-boleadora/divisora-boleadora-semiautomatica",
        destination: "/es/divisora-boleadora-semiautomatica",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/sigep-ab-tech-expo-2020",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-industrial",
        destination: "/es/cortadoras-de-pan-industriales",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadora-de-masa/laminadora-pizza",
        destination: "/es/sectores/pizza",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-de-mostrador",
        destination: "/es/cortadoras-semiautomaticas-de-pan-de-paso-fijo",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/video-abtech-sigep-2013",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/levantador-y-cubas",
        destination: "/es/levantador-y-cubas-para-mezcladores-planetarios",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/mesas",
        destination: "/es/mesas-de-trabajo-para-laminadoras",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/bakery-china-expo-2019",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadora-de-masa/laminadora-panaderia",
        destination: "/es/sectores/panaderia",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/video-sigep-ab-tech-expo-2017",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-de-pan-de-paso-variable",
        destination: "/es/cortadoras-automaticas-de-pan-de-paso-variable",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidora-planetaria/amasadora-planetaria",
        destination: "/es/batidoras-planetarias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/trituradora-de-pan",
        destination: "/es/molino-de-pan-profesional",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-automaticas/r65axp-r65axp-t",
        destination: "/es/laminadoras/r65axp-r65axp-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales-compactas",
        destination: "/es/laminadoras-manuales",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/host-2019",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/melbourne-1st-prize-for-the-innovation",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-con-base",
        destination: "/es/cortadoras-semiautomaticas-de-pan-de-paso-fijo",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidora-planetaria",
        destination: "/es/batidoras-planetarias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/intersicop-2019",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/video-abtech-sigep-2015",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/divisora-boleadora/divisora-boleadora-manual",
        destination: "/es/divisora-boleadora-manual",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/video-diro-cortadoras-boleadoras",
        destination: "/es/divisora-boleadora",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-semi-automaticas",
        destination: "/es/laminadoras-semiautomaticas",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/sopladora-en-inox-para-el-embolsado",
        destination: "/es/sopladora-en-inox-para-el-embolsado",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/mezcladores-planetarios/b60-b60p",
        destination: "/es/batidoras-planetarias/b60-b60p",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-de-pan-de-paso-variable/s40s-s50s",
        destination: "/es/cortadoras-de-pan/s40-s-s50-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/trituradora-de-pan/bm11",
        destination: "/es/cortadoras-de-pan/bm11",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/r65axp-4-0",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-de-mostrador/c42-c52",
        destination: "/es/cortadoras-de-pan/c42-c52",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-de-mostrador/cp42-pl",
        destination: "/es/cortadoras-de-pan/cp42-pl",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/noticias/nueva-generacion-de-cortadoras-de-pan-con-paso-variable",
        destination: "/es/noticias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-de-mostrador/cp42-cp52",
        destination: "/es/cortadoras-de-pan/cp42-cp52",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-industrial/mr52",
        destination: "/es/cortadoras-de-pan/mr52",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-con-base/c42s-c52s",
        destination: "/es/cortadoras-de-pan/c42-s-c52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/divisora-boleadora/divisora-boleadora-manual/dr-m",
        destination: "/es/divisora-boleadora/dr-m",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-con-base/cp42s-cp52s",
        destination: "/es/cortadoras-de-pan/cp42-s-cp52-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/divisora-boleadora/divisora-boleadora-automatica/dr-a",
        destination: "/es/divisora-boleadora/dr-a",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-de-pan-de-paso-variable/s40-s50",
        destination: "/es/cortadoras-de-pan/s40-s50",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/mezcladores-planetarios/b40l-b40p",
        destination: "/es/batidoras-planetarias/b40p",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/levantador-y-cubas/soll-100-160",
        destination: "/es/batidoras-planetarias/soll100-soll160",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-industrial/mi52",
        destination: "/es/cortadoras-de-pan/mi52",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/mezcladores-planetarios/b60l",
        destination: "/es/batidoras-planetarias/b60l",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales-compactas/r55b",
        destination: "/es/laminadoras/r55b",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/cortadoras-de-mostrador/g42",
        destination: "/es/cortadoras-de-pan/g42",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-automaticas/r65a-r65a-t",
        destination: "/es/laminadoras/r65a-r65a-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales/r65-r65-t",
        destination: "/es/laminadoras/r65-r65-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales/r62-r62-t",
        destination: "/es/laminadoras/r62-r62-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales-compactas/r55",
        destination: "/es/laminadoras/r55",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/mezcladores-planetarios/b10",
        destination: "/es/batidoras-planetarias",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/divisora-boleadora/divisora-boleadora-semiautomatica/dr-s",
        destination: "/es/divisora-boleadora/dr-s",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/sopladora-en-inox-para-el-embolsado/aps-fs",
        destination: "/es/cortadoras-de-pan/aps-fs",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/cortadoras/trituradora-de-pan/mac100",
        destination: "/es/cortadoras-de-pan/mac100",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-automaticas/r65ax-r65ax-t",
        destination: "/es/laminadoras/r65ax-r65ax-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales-compactas/s5bm",
        destination: "/es/laminadoras/s5bm",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/mezcladores-planetarios/b100-b160",
        destination: "/es/batidoras-planetarias/b100-b160",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales-compactas/r50b",
        destination: "/es/laminadoras/r50b",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/mesas/tb30-35",
        destination: "/es/laminadoras/tb30-tb35",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales/r60-r60-t",
        destination: "/es/laminadoras/r60-r60-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-semi-automaticas/r65s-r65s-t",
        destination: "/es/laminadoras/r65s-r65s-t",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/batidoras/mezcladores-planetarios/b80l",
        destination: "/es/batidoras-planetarias/b80l",
        permanent: true,
        locale: false,
      },
      {
        source: "/es/laminadoras/laminadoras-manuales-compactas/r50",
        destination: "/es/laminadoras/r50",
        permanent: true,
        locale: false,
      },
      // ===== РУССКИЙ (79) =====
      // -> /ru/планетарные-миксеры
      {
        source: "/ru/mixers",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b",
        permanent: true,
        locale: false,
      },
      {
        source: "/ru/privacy",
        destination: "/ru",
        permanent: true,
        locale: false,
      },
      {
        source: "/ru/sitemap",
        destination: "/ru",
        permanent: true,
        locale: false,
      },
      // -> /ru/готово-к-доставке
      {
        source: "/ru/available-in-stock",
        destination: "/ru/%d0%b3%d0%be%d1%82%d0%be%d0%b2%d0%be-%d0%ba-%d0%b4%d0%be%d1%81%d1%82%d0%b0%d0%b2%d0%ba%d0%b5",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины
      {
        source: "/ru/slicers",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b",
        permanent: true,
        locale: false,
      },
      {
        source: "/ru/sales-terms-and-conditions",
        destination: "/ru",
        permanent: true,
        locale: false,
      },
      // -> /ru/делитель-округлитель-теста
      {
        source: "/ru/divider-rounders",
        destination: "/ru/%d0%b4%d0%b5%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d0%be%d0%ba%d1%80%d1%83%d0%b3%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d1%82%d0%b5%d1%81%d1%82%d0%b0",
        permanent: true,
        locale: false,
      },
      // -> /ru/агентство
      {
        source: "/ru/company-profile",
        destination: "/ru/%d0%b0%d0%b3%d0%b5%d0%bd%d1%82%d1%81%d1%82%d0%b2%d0%be",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины
      {
        source: "/ru/sheeters",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b",
        permanent: true,
        locale: false,
      },
      // -> /ru/контакты
      {
        source: "/ru/contacts",
        destination: "/ru/%d0%ba%d0%be%d0%bd%d1%82%d0%b0%d0%ba%d1%82%d1%8b",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      {
        source: "/ru/news/host-2025",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8/host-2025",
        permanent: true,
        locale: false,
      },
      {
        source: "/ru/legal-notes",
        destination: "/ru",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/blog-news",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      {
        source: "/ru/disclaimer",
        destination: "/ru",
        permanent: true,
        locale: false,
      },
      // -> /ru/рабочие-столы-для-тестораскаточных-м
      {
        source: "/ru/sheeters/tables",
        destination: "/ru/%d1%80%d0%b0%d0%b1%d0%be%d1%87%d0%b8%d0%b5-%d1%81%d1%82%d0%be%d0%bb%d1%8b-%d0%b4%d0%bb%d1%8f-%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d1%85-%d0%bc",
        permanent: true,
        locale: false,
      },
      // -> /ru/полуавтоматические-тестораскаточны
      {
        source: "/ru/sheeters/semi-automatic-dough-sheeters",
        destination: "/ru/%d0%bf%d0%be%d0%bb%d1%83%d0%b0%d0%b2%d1%82%d0%be%d0%bc%d0%b0%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b5-%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b",
        permanent: true,
        locale: false,
      },
      // -> /ru/профессиональные-тестораскаточные-м
      {
        source: "/ru/sheeters/manual-compact-dough-sheeters",
        destination: "/ru/%d0%bf%d1%80%d0%be%d1%84%d0%b5%d1%81%d1%81%d0%b8%d0%be%d0%bd%d0%b0%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc",
        permanent: true,
        locale: false,
      },
      // -> /ru/планетарные-миксеры
      {
        source: "/ru/mixers/planetary-mixers/b10",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/mr52
      {
        source: "/ru/slicers/industrial-bread-slicers/mr52",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/mr52",
        permanent: true,
        locale: false,
      },
      // -> /ru/автоматические-хлеборезки-с-регулир
      {
        source: "/ru/slicers/bread-slicers-variable-pitch",
        destination: "/ru/%d0%b0%d0%b2%d1%82%d0%be%d0%bc%d0%b0%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b5-%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%ba%d0%b8-%d1%81-%d1%80%d0%b5%d0%b3%d1%83%d0%bb%d0%b8%d1%80",
        permanent: true,
        locale: false,
      },
      // -> /ru/промышленные-хлеборезательные-машин
      {
        source: "/ru/slicers/industrial-bread-slicers",
        destination: "/ru/%d0%bf%d1%80%d0%be%d0%bc%d1%8b%d1%88%d0%bb%d0%b5%d0%bd%d0%bd%d1%8b%d0%b5-%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/aps-fs
      {
        source: "/ru/slicers/bag-blower-for-packaging/aps-fs",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/aps-fs",
        permanent: true,
        locale: false,
      },
      // -> /ru/планетарные-миксеры/b60l
      {
        source: "/ru/mixers/planetary-mixers/b60l",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b/b60l",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r65a-r65a-t
      {
        source: "/ru/sheeters/automatic-dough-sheeters/r65a-r65a-t",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r65a-r65a-t",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r65-r65-t
      {
        source: "/ru/sheeters/manual-dough-sheeters/r65-r65-t",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r65-r65-t",
        permanent: true,
        locale: false,
      },
      // -> /ru/воздуходувка-для-упаковки-хлеба-в-пак
      {
        source: "/ru/slicers/bag-blower-for-packaging",
        destination: "/ru/%d0%b2%d0%be%d0%b7%d0%b4%d1%83%d1%85%d0%be%d0%b4%d1%83%d0%b2%d0%ba%d0%b0-%d0%b4%d0%bb%d1%8f-%d1%83%d0%bf%d0%b0%d0%ba%d0%be%d0%b2%d0%ba%d0%b8-%d1%85%d0%bb%d0%b5%d0%b1%d0%b0-%d0%b2-%d0%bf%d0%b0%d0%ba",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/s40-s-s50-s
      {
        source: "/ru/slicers/bread-slicers-variable-pitch/s40s-s50s",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/s40-s-s50-s",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/cp42-pl
      {
        source: "/ru/slicers/bench-type-bread-slicers/cp42-pl",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/cp42-pl",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/c42-c52
      {
        source: "/ru/slicers/bench-type-bread-slicers/c42-c52",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/c42-c52",
        permanent: true,
        locale: false,
      },
      // -> /ru/автоматический-делитель-округлитель
      {
        source: "/ru/divider-rounders/automatic-divider-rounder",
        destination: "/ru/%d0%b0%d0%b2%d1%82%d0%be%d0%bc%d0%b0%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b9-%d0%b4%d0%b5%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d0%be%d0%ba%d1%80%d1%83%d0%b3%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c",
        permanent: true,
        locale: false,
      },
      // -> /ru/планетарные-миксеры
      {
        source: "/ru/mixers/planetary-mixers",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b",
        permanent: true,
        locale: false,
      },
      // -> /ru/делитель-округлитель-теста/dr-s
      {
        source: "/ru/divider-rounders/semi-automatic-divider-rounder/dr-s",
        destination: "/ru/%d0%b4%d0%b5%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d0%be%d0%ba%d1%80%d1%83%d0%b3%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d1%82%d0%b5%d1%81%d1%82%d0%b0/dr-s",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r65ax-r65ax-t
      {
        source: "/ru/sheeters/automatic-dough-sheeters/r65ax-r65ax-t",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r65ax-r65ax-t",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/cp42-cp52
      {
        source: "/ru/slicers/bench-type-bread-slicers/cp42-cp52",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/cp42-cp52",
        permanent: true,
        locale: false,
      },
      // -> /ru/планетарные-миксеры/b40p
      {
        source: "/ru/mixers/planetary-mixers/b40l-b40p",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b/b40p",
        permanent: true,
        locale: false,
      },
      // -> /ru/планетарные-миксеры/b60-b60p
      {
        source: "/ru/mixers/planetary-mixers/b60-b60p",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b/b60-b60p",
        permanent: true,
        locale: false,
      },
      // -> /ru/полуавтоматические-хлеборезательны
      {
        source: "/ru/slicers/free-standing-bread-slicers",
        destination: "/ru/%d0%bf%d0%be%d0%bb%d1%83%d0%b0%d0%b2%d1%82%d0%be%d0%bc%d0%b0%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b5-%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b",
        permanent: true,
        locale: false,
      },
      // -> /ru/полуавтоматические-хлеборезательны
      {
        source: "/ru/slicers/bench-type-bread-slicers",
        destination: "/ru/%d0%bf%d0%be%d0%bb%d1%83%d0%b0%d0%b2%d1%82%d0%be%d0%bc%d0%b0%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b5-%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b",
        permanent: true,
        locale: false,
      },
      // -> /ru/планетарные-миксеры/b100-b160
      {
        source: "/ru/mixers/planetary-mixers/b100-b160",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b/b100-b160",
        permanent: true,
        locale: false,
      },
      // -> /ru/делитель-округлитель-теста/dr-a
      {
        source: "/ru/divider-rounders/automatic-divider-rounder/dr-a",
        destination: "/ru/%d0%b4%d0%b5%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d0%be%d0%ba%d1%80%d1%83%d0%b3%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d1%82%d0%b5%d1%81%d1%82%d0%b0/dr-a",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r55b
      {
        source: "/ru/sheeters/manual-compact-dough-sheeters/r55b",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r55b",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/mac100
      {
        source: "/ru/slicers/bread-mill/mac100",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/mac100",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/cp42-s-cp52-s
      {
        source: "/ru/slicers/free-standing-bread-slicers/cp42s-cp52s",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/cp42-s-cp52-s",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r65s-r65s-t
      {
        source: "/ru/sheeters/semi-automatic-dough-sheeters/r65s-r65s-t",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r65s-r65s-t",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r62-r62-t
      {
        source: "/ru/sheeters/manual-dough-sheeters/r62-r62-t",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r62-r62-t",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r50
      {
        source: "/ru/sheeters/manual-compact-dough-sheeters/r50",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r50",
        permanent: true,
        locale: false,
      },
      // -> /ru/профессиональные-хлебные-мельницы
      {
        source: "/ru/slicers/bread-mill",
        destination: "/ru/%d0%bf%d1%80%d0%be%d1%84%d0%b5%d1%81%d1%81%d0%b8%d0%be%d0%bd%d0%b0%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d1%85%d0%bb%d0%b5%d0%b1%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b5%d0%bb%d1%8c%d0%bd%d0%b8%d1%86%d1%8b",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/tb30-tb35
      {
        source: "/ru/sheeters/tables/tb30-35",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/tb30-tb35",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/c42-s-c52-s
      {
        source: "/ru/slicers/free-standing-bread-slicers/c42s-c52s",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/c42-s-c52-s",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r60-r60-t
      {
        source: "/ru/sheeters/manual-dough-sheeters/r60-r60-t",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r60-r60-t",
        permanent: true,
        locale: false,
      },
      // -> /ru/планетарные-миксеры/b80l
      {
        source: "/ru/mixers/planetary-mixers/b80l",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b/b80l",
        permanent: true,
        locale: false,
      },
      // -> /ru/ручной-делитель-округлитель-теста
      {
        source: "/ru/divider-rounders/manual-divider-rounder",
        destination: "/ru/%d1%80%d1%83%d1%87%d0%bd%d0%be%d0%b9-%d0%b4%d0%b5%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d0%be%d0%ba%d1%80%d1%83%d0%b3%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d1%82%d0%b5%d1%81%d1%82%d0%b0",
        permanent: true,
        locale: false,
      },
      // -> /ru/полуавтоматический-делитель-округли
      {
        source: "/ru/divider-rounders/semi-automatic-divider-rounder",
        destination: "/ru/%d0%bf%d0%be%d0%bb%d1%83%d0%b0%d0%b2%d1%82%d0%be%d0%bc%d0%b0%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b9-%d0%b4%d0%b5%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d0%be%d0%ba%d1%80%d1%83%d0%b3%d0%bb%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r55
      {
        source: "/ru/sheeters/manual-compact-dough-sheeters/r55",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r55",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/bm11
      {
        source: "/ru/slicers/bread-mill/bm11",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/bm11",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r65axp-r65axp-t
      {
        source: "/ru/sheeters/automatic-dough-sheeters/r65axp-r65axp-t",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r65axp-r65axp-t",
        permanent: true,
        locale: false,
      },
      // -> /ru/подъемники-дежи-для-планетарных-микс
      {
        source: "/ru/mixers/bowl-lifter-planetary-mixers",
        destination: "/ru/%d0%bf%d0%be%d0%b4%d1%8a%d0%b5%d0%bc%d0%bd%d0%b8%d0%ba%d0%b8-%d0%b4%d0%b5%d0%b6%d0%b8-%d0%b4%d0%bb%d1%8f-%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d1%85-%d0%bc%d0%b8%d0%ba%d1%81",
        permanent: true,
        locale: false,
      },
      // -> /ru/делитель-округлитель-теста/dr-m
      {
        source: "/ru/divider-rounders/manual-divider-rounder/dr-m",
        destination: "/ru/%d0%b4%d0%b5%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d0%be%d0%ba%d1%80%d1%83%d0%b3%d0%bb%d0%b8%d1%82%d0%b5%d0%bb%d1%8c-%d1%82%d0%b5%d1%81%d1%82%d0%b0/dr-m",
        permanent: true,
        locale: false,
      },
      // -> /ru/профессиональные-тестораскаточные-м
      {
        source: "/ru/sheeters/manual-dough-sheeters",
        destination: "/ru/%d0%bf%d1%80%d0%be%d1%84%d0%b5%d1%81%d1%81%d0%b8%d0%be%d0%bd%d0%b0%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/r50b
      {
        source: "/ru/sheeters/manual-compact-dough-sheeters/r50b",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/r50b",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/g42
      {
        source: "/ru/slicers/bench-type-bread-slicers/g42",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/g42",
        permanent: true,
        locale: false,
      },
      // -> /ru/тестораскаточные-машины/s5bm
      {
        source: "/ru/sheeters/manual-compact-dough-sheeters/s5bm",
        destination: "/ru/%d1%82%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d1%81%d0%ba%d0%b0%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/s5bm",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/mi52
      {
        source: "/ru/slicers/industrial-bread-slicers/mi52",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/mi52",
        permanent: true,
        locale: false,
      },
      // -> /ru/профессиональные-автоматические-тес
      {
        source: "/ru/sheeters/automatic-dough-sheeters",
        destination: "/ru/%d0%bf%d1%80%d0%be%d1%84%d0%b5%d1%81%d1%81%d0%b8%d0%be%d0%bd%d0%b0%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%b0%d0%b2%d1%82%d0%be%d0%bc%d0%b0%d1%82%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b5-%d1%82%d0%b5%d1%81",
        permanent: true,
        locale: false,
      },
      // -> /ru/хлеборезательные-машины/s40-s50
      {
        source: "/ru/slicers/bread-slicers-variable-pitch/s40-s50",
        destination: "/ru/%d1%85%d0%bb%d0%b5%d0%b1%d0%be%d1%80%d0%b5%d0%b7%d0%b0%d1%82%d0%b5%d0%bb%d1%8c%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d1%8b/s40-s50",
        permanent: true,
        locale: false,
      },
      // -> /ru/планетарные-миксеры/soll100-soll160
      {
        source: "/ru/mixers/bowl-lifter-planetary-mixers/soll-100-160",
        destination: "/ru/%d0%bf%d0%bb%d0%b0%d0%bd%d0%b5%d1%82%d0%b0%d1%80%d0%bd%d1%8b%d0%b5-%d0%bc%d0%b8%d0%ba%d1%81%d0%b5%d1%80%d1%8b/soll100-soll160",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/sigep-abtech-2023",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/iba-2025",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/sigep-ab-tech-expo-2020",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/video-abtech-sigep-2013",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/bakery-china-expo-2019",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/video-sigep-ab-tech-expo-2017",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/video-abtech-sigep-2015",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/intersicop-2019",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/host-2019",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/melbourne-1st-prize-for-the-innovation",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/r65axp-4-0",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
      // -> /ru/новости
      {
        source: "/ru/news/new-generation-of-bread-slicers-with-variable-pitch",
        destination: "/ru/%d0%bd%d0%be%d0%b2%d0%be%d1%81%d1%82%d0%b8",
        permanent: true,
        locale: false,
      },
    ];
  },
};


export default withNextIntl(nextConfig);
